### ISSUE TITLE
Text 

### ISSUE THREAD

**Issue by Twork-tw** [ianmsfvenom/Brizas-bot#6]
O .text só tá dando erro, não faz a imágem com o texto

**Comment by ianmsfvenom** [comment]
amigo esse comando nem existe no bot

**Comment by Twork-tw** [comment]
Tava falando do comando que transforma texto em imagem, mas entendo vlw
amigo

Em qua, 27 de jan de 2021 22:32, Br!z@l0k@ <notifications@github.com>
escreveu:
